version: '3.5'
services:

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
          - 2181:2181
        volumes:
          - ./configs/scram/zookeeper_server_jaas.conf:/etc/kafka/config/zookeeper_server_jaas.conf
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/config/zookeeper_server_jaas.conf
                # -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
                # -Dzookeeper.allowSaslFailedClients=false
                # -Dzookeeper.requireClientAuthScheme=sasl

    broker:
        image: confluentinc/cp-kafka:latest
        volumes:
          - ./configs/scram/kafka_server_jaas.conf:/etc/kafka/config/kafka_server_jaas.conf
          - ./configs/scram/client.properties:/etc/kafka/client.properties
          - ./configs/scram/client.properties:/tmp/client.properties
        depends_on:
          - zookeeper
        ports:
          - '9092:9092'
          - '9093:9093'
        environment:
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,SASL_PLAINTEXT://0.0.0.0:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,SASL_PLAINTEXT://broker:9093
            KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
            KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
            KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
            KAFKA_LISTENER_NAME_SASL_SSL_SCRAM_SHA_256_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"admin\" \
                password=\"admin_secret\";"
            KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/config/kafka_server_jaas.conf"

    connect:
        image: confluentinc/cp-kafka-connect:latest
        hostname: connect
        container_name: connect
        restart: always
        depends_on:
          - broker
          - schema-registry
          - zookeeper
        ports:
          - "5005:5005"
          - "8083:8083"
          - "10002:10002"
        volumes:
          - ./configs/scram/client.properties:/etc/kafka/client.properties
          - ./configs/scram/client.properties:/tmp/client.properties
        environment:
            # Configure the Connect workers to use SASL/SCRAM-SHA-256.
            CONNECT_SASL_MECHANISM: SCRAM-SHA-256
            CONNECT_SECURITY_PROTOCOL: SASL_PLAINTEXT
            # JAAS
            CONNECT_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            # producer
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: SCRAM-SHA-256
            # consumer
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: SCRAM-SHA-256
            # producer
            CONNECT_PRODUCER_SASL_MECHANISM: SCRAM-SHA-256
            CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_PRODUCER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            # consumer
            CONNECT_CONSUMER_SASL_MECHANISM: SCRAM-SHA-256
            CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_CONSUMER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"

    schema-registry:
        image: confluentinc/cp-schema-registry:latest
        hostname: schema-registry
        container_name: schema-registry
        restart: always
        depends_on:
          - broker
        ports:
          - "8081:8081"
          - "10001:10001"
        volumes:
          - ./configs/scram/client.properties:/etc/kafka/client.properties
          - ./configs/scram/client.properties:/tmp/client.properties
        environment:
            SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_PLAINTEXT
            SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: SCRAM-SHA-256
            SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"schemaregistry\" \
                password=\"schemaregistry-secret\";"

    ksqldb-server: 
        image: confluentinc/cp-ksql-server:latest
        hostname: ksqldb-server
        container_name: ksqldb-server
        depends_on:
          - broker
          - connect
        ports:
          - "8088:8088"
          - "10003:10003"
        profiles:
        - ksqldb
        environment:
            KSQL_SECURITY_PROTOCOL: SASL_PLAINTEXT
            KSQL_SASL_MECHANISM: SCRAM-SHA-256
            KSQL_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"ksqldb\" \
                password=\"ksqldb-secret\";"
            # producer
            KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"ksqldb\" \
                password=\"ksqldb-secret\";"
            KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: SCRAM-SHA-256
            # consumer
            KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"ksqldb\" \
                password=\"ksqldb-secret\";"
            KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: SCRAM-SHA-256

    control-center:
        image: confluentinc/cp-enterprise-control-center:latest
        hostname: control-center
        container_name: control-center
        restart: always
        depends_on:
          - broker
          - schema-registry
          - connect
        profiles:
          - control-center
        environment:
            CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:9092'
            CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            CONTROL_CENTER_CONNECT_CLUSTER: http://connect:8083 # deprecated
            CONTROL_CENTER_CONNECT_MYCONNECT_CLUSTER: http://connect:8083
            CONTROL_CENTER_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'
            CONTROL_CENTER_REPLICATION_FACTOR: 1
            CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
            CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
            CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
            CONFLUENT_METRICS_TOPIC_REPLICATION: 1
            CONTROL_CENTER_KAFKA_MYCLUSTER_BOOTSTRAP_SERVERS: 'broker:9092'
            CONTROL_CENTER_UI_AUTOUPDATE_ENABLE: "false"
            CONTROL_CENTER_KSQL_URL: "http://ksqldb-server:8088" # deprecated
            CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://127.0.0.1:8088" # deprecated
            CONTROL_CENTER_KSQL_MYKSQL_URL: "http://ksqldb-server:8088"
            CONTROL_CENTER_KSQL_MYKSQL_ADVERTISED_URL: "http://127.0.0.1:8088"
            CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
            CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 1
            CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"client\" \
                password=\"client-secret\";"
            CONTROL_CENTER_STREAMS_SASL_MECHANISM: SCRAM-SHA-256

            CONTROL_CENTER_KAFKA_MYCLUSTER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONTROL_CENTER_KAFKA_MYCLUSTER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required \
                username=\"client\" \
                password=\"client-secret\";"
            CONTROL_CENTER_KAFKA_MYCLUSTER_SASL_MECHANISM: SCRAM-SHA-256

    # https://github.com/conduktor/conduktor-platform/blob/main/doc/Configuration.md
    conduktor:
        image: conduktor/conduktor-platform:latest
        hostname: conduktor
        container_name: conduktor
        depends_on:
          - broker
        volumes:
          - ../configs/scram/platform-config.yaml:/tmp/platform-config.yaml